In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/HKHJ_Dataset_Feature_Engineered.csv')

In [3]:
df.shape

(158563, 60)

In [4]:
df.head()

,date,location,race_no,info,going,course,place,horse_number,horse_name,horse_name_id,...,performance_within_race_trend,performance_within_race_trend_confidence,performance_within_conditions_trend,performance_within_conditions_trend_confidence,on_date_horse_weight_trend,on_date_horse_weight_trend_confidence,on_date_horse_weight_trend_direction,weight_trend,weight_trend_confidence,weight_trend_direction
0,2009-01-01 00:00:00+08:00,Sha Tin,RACE 1 (264),Class 4 - 1600M - (60-40),GOOD TO FIRM,"TURF - ""B+2"" Course",1,1.0,BEAUTIFUL CHOICE(CH130),CH130,...,NaN,0.0,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN
1,2009-01-01 00:00:00+08:00,Sha Tin,RACE 1 (264),Class 4 - 1600M - (60-40),GOOD TO FIRM,"TURF - ""B+2"" Course",2,9.0,LIVERBIRD(CE055),CE055,...,NaN,0.0,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN
2,2009-01-01 00:00:00+08:00,Sha Tin,RACE 1 (264),Class 4 - 1600M - (60-40),GOOD TO FIRM,"TURF - ""B+2"" Course",3,10.0,GREEN GLORY(CJ177),CJ177,...,NaN,0.0,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN
3,2009-01-01 00:00:00+08:00,Sha Tin,RACE 1 (264),Class 4 - 1600M - (60-40),GOOD TO FIRM,"TURF - ""B+2"" Course",4,4.0,BRILLIANT FLASH(CE042),CE042,...,NaN,0.0,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN
4,2009-01-01 00:00:00+08:00,Sha Tin,RACE 1 (264),Class 4 - 1600M - (60-40),GOOD TO FIRM,"TURF - ""B+2"" Course",5,2.0,DR WELL(CD165),CD165,...,NaN,0.0,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN

In [5]:
df.isna().sum()

date                                                  0
location                                              0
race_no                                               0
info                                                  0
going                                                 0
course                                                0
place                                                 0
horse_number                                       1608
horse_name                                            0
horse_name_id                                         0
jockey                                                0
trainer                                               0
weight                                                0
on_date_horse_weight                               2967
draw                                               2958
length_behind_winner                               3399
running_position                                      0
finish_time                                           0
win_odds                                           2967
race_id_number                                        0
race_id_year                                          0
info_class                                            0
info_distance                                         0
info_rating                                        6920
surface_type                                          0
rail_offset                                           0
place_numeric                                      3287
finish_time_seconds                                3276
speed_normalized                                      0
unique_id                                             0
performance_within_race                            3276
performance_within_conditions                      3768
top3                                                  0
win                                                   0
season                                                0
races_in_season                                       0
days_since_last_race_any                           8493
days_since_last_race_same_season                  21867
performance_within_race_rolling_mean_5            22214
performance_within_race_rolling_median_5          22214
performance_within_race_rolling_count_5               0
performance_within_race_ewa_5                     22214
performance_within_conditions_rolling_mean_5      22233
performance_within_conditions_rolling_median_5    22233
performance_within_conditions_rolling_count_5         0
performance_within_conditions_ewa_5               22233
place_numeric_rolling_mean_5                      22214
place_numeric_rolling_median_5                    22214
place_numeric_rolling_count_5                         0
place_numeric_ewa_5                               22214
performance_within_race_trend                     42412
performance_within_race_trend_confidence              0
performance_within_conditions_trend               42436
performance_within_conditions_trend_confidence        0
on_date_horse_weight_trend                        22589
on_date_horse_weight_trend_confidence                 0
on_date_horse_weight_trend_direction              22589
weight_trend                                      21867
weight_trend_confidence                               0
weight_trend_direction                            21867
dtype: int64

### Variables that should be retained
- date
- location
- going
- place
- horse_number
- horse_name_id (create a dict here)
- jockey
- trainer
- weight
- on_date_horse_weight
- draw
- info_class
- info_distance
- info_rating
- surface_type
- rail_offset
- unique_id
- season
- races_in_season
- days_since_last_race_any
- days_since_last_race_same_season
- performance_within_race_rolling_mean_5
- performance_within_race_rolling_median_5
- performance_within_race_ewa_5
- performance_within_conditions_rolling_mean_5
- performance_within_conditions_rolling_median_5
- performance_within_conditions_rolling_count_5
- performance_within_conditions_ewa_5
- place_numeric_rolling_mean_5
- place_numeric_rolling_median_5
- place_numeric_rolling_count_5
- place_numeric_ewa_5
- performance_within_race_trend
- performance_within_race_trend_confidence
- performance_within_conditions_trend
- performance_within_conditions_trend_confidence
- on_date_horse_weight_trend
- on_date_horse_weight_trend_confidence
- on_date_horse_weight_trend_direction
- weight_trend
- weight_trend_confidence
- weight_trend_direction
- top3
- win

Next, we create a new dataframe with these columns

In [6]:
ml_columns = [
"date",
"location",
"going",
"horse_number",
"horse_name_id",
"jockey",
"trainer",
"weight",
"on_date_horse_weight",
"draw",
"info_class",
"info_distance",
"info_rating",  
"surface_type",
"rail_offset",
"unique_id",
"season",
"races_in_season",
"days_since_last_race_any",
"days_since_last_race_same_season",
"performance_within_race_rolling_mean_5",
"performance_within_race_rolling_median_5",
"performance_within_race_ewa_5",
"performance_within_conditions_rolling_mean_5",
"performance_within_conditions_rolling_median_5",
"performance_within_conditions_rolling_count_5",
"performance_within_conditions_ewa_5",
"place_numeric_rolling_mean_5",
"place_numeric_rolling_median_5",
"place_numeric_rolling_count_5",
"place_numeric_ewa_5",
"performance_within_race_trend",
"performance_within_race_trend_confidence",
"performance_within_conditions_trend",
"performance_within_conditions_trend_confidence",
"on_date_horse_weight_trend",
"on_date_horse_weight_trend_confidence",
"on_date_horse_weight_trend_direction",
"weight_trend",
"weight_trend_confidence",
"weight_trend_direction",
"top3",
"win"
]

In [7]:
df_new = df[ml_columns]

In [8]:
df_new.head()

,date,location,going,horse_number,horse_name_id,jockey,trainer,weight,on_date_horse_weight,draw,...,performance_within_conditions_trend,performance_within_conditions_trend_confidence,on_date_horse_weight_trend,on_date_horse_weight_trend_confidence,on_date_horse_weight_trend_direction,weight_trend,weight_trend_confidence,weight_trend_direction,top3,win
0,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,1.0,CH130,K C Leung,Y S Tsui,119,1114.0,4.0,...,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN,1,1
1,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,9.0,CE055,H W Lai,C S Shum,118,1125.0,8.0,...,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN,1,0
2,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,10.0,CJ177,W C Marwing,P F Yiu,118,1063.0,2.0,...,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN,1,0
3,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,4.0,CE042,O Doleuze,C Fownes,127,1144.0,9.0,...,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN,0,0
4,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,2.0,CD165,M L Yeung,C W Chang,118,1122.0,6.0,...,NaN,0.0,NaN,0.2,NaN,NaN,0.2,NaN,0,0

In [9]:
for col in df_new.select_dtypes(include=['object']).columns:
    print(f"Column: {col}")

Column: date
Column: location
Column: going
Column: horse_name_id
Column: jockey
Column: trainer
Column: info_class
Column: info_rating
Column: surface_type

In [10]:
df_new['location'].unique()

array(['Sha Tin', 'Happy Valley'], dtype=object)

In [11]:
df_new['going'].unique()

array(['GOOD TO FIRM', 'FAST', 'GOOD', 'GOOD TO YIELDING', 'YIELDING',
       'SOFT', 'WET SLOW', 'YIELDING TO SOFT', 'SLOW', 'WET FAST',
       'HEAVY', 'SEALED'], dtype=object)

In [12]:
df_new['info_class'].unique()

array(['Class 4', 'Class 5', 'Class 3', 'Class 2',
       'Hong Kong Group Three', 'Class 1', 'Class 4 (Special Condition)',
       'Hong Kong Group One', 'Class 4 (Bonus Prize Money)',
       'Class 2 (Bonus Prize Money)', 'Class 3 (Bonus Prize Money)',
       'Griffin Race', 'Hong Kong Group Two', 'Restricted Race',
       'Class 3 (Special Condition)', 'Group One', 'Group Two',
       'Class 4 (Restricted)', 'Group Three', '4 Year Olds',
       'Class 3 (Restricted)'], dtype=object)

In [13]:
df_new['info_rating'].unique()

array(['60-40', '40-10', '40-0', '80-60', '95-75', nan, '85-60', '100-80',
       '110-90', '90-70', '65-40', '110-85', '105-80', '115-90', '100-75',
       '115-95', '75-55', '40-15', '120-95', '95-70', '105-85', '120-100',
       '40-20', '60-35', '80-55', '110-80', '95-80', '100-70', '105-75',
       '90-65', '90-60'], dtype=object)

In [14]:
df_new['surface_type'].unique()

array(['TURF', 'AWT'], dtype=object)

In [15]:
location_mapping = {
    'Happy Valley': 0,
    'Sha Tin': 1
}

## Mapping Surface Type and Going

In [16]:
df_new[df_new['surface_type'] == 'AWT']['going'].unique()

array(['FAST', 'GOOD', 'WET SLOW', 'SLOW', 'WET FAST', 'SEALED'],
      dtype=object)

In [17]:
df_new[df_new['surface_type'] == 'TURF']['going'].unique()

array(['GOOD TO FIRM', 'GOOD', 'GOOD TO YIELDING', 'YIELDING', 'SOFT',
       'YIELDING TO SOFT', 'HEAVY'], dtype=object)

In [18]:
awt_mapping = {
    'FAST': 0, 
    'GOOD': 1,
    'WET SLOW': 2, 
    'SLOW': 3, 
    'WET FAST': 4, 
    'SEALED': 5
}
turf_mapping = {
    'GOOD TO FIRM': 0, 
    'GOOD': 1, 
    'GOOD TO YIELDING': 2,
    'YIELDING': 3, 
    'YIELDING TO SOFT': 4, 
    'SOFT': 5, 
    'HEAVY': 6
}

In [19]:
df_new['surface_type_mapped'] = (df['surface_type'].str.upper() == 'AWT').astype('int8')

/var/folders/ry/3xn1jktn0j33gx31vxb5brvr0000gn/T/ipykernel_30562/3552608840.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['surface_type_mapped'] = (df['surface_type'].str.upper() == 'AWT').astype('int8')

In [20]:
df_new['going_numeric'] = np.where(
    df_new['surface_type_mapped'] == 1,
    df_new['going'].map(awt_mapping),
    df_new['going'].map(turf_mapping)
)

/var/folders/ry/3xn1jktn0j33gx31vxb5brvr0000gn/T/ipykernel_30562/1176366735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['going_numeric'] = np.where(

In [21]:
df_new.head()

,date,location,going,horse_number,horse_name_id,jockey,trainer,weight,on_date_horse_weight,draw,...,on_date_horse_weight_trend,on_date_horse_weight_trend_confidence,on_date_horse_weight_trend_direction,weight_trend,weight_trend_confidence,weight_trend_direction,top3,win,surface_type_mapped,going_numeric
0,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,1.0,CH130,K C Leung,Y S Tsui,119,1114.0,4.0,...,NaN,0.2,NaN,NaN,0.2,NaN,1,1,0,0.0
1,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,9.0,CE055,H W Lai,C S Shum,118,1125.0,8.0,...,NaN,0.2,NaN,NaN,0.2,NaN,1,0,0,0.0
2,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,10.0,CJ177,W C Marwing,P F Yiu,118,1063.0,2.0,...,NaN,0.2,NaN,NaN,0.2,NaN,1,0,0,0.0
3,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,4.0,CE042,O Doleuze,C Fownes,127,1144.0,9.0,...,NaN,0.2,NaN,NaN,0.2,NaN,0,0,0,0.0
4,2009-01-01 00:00:00+08:00,Sha Tin,GOOD TO FIRM,2.0,CD165,M L Yeung,C W Chang,118,1122.0,6.0,...,NaN,0.2,NaN,NaN,0.2,NaN,0,0,0,0.0

## Encoding Horse Name, Jockey and Trainer

In [22]:
new_df = df_new.sort_values('date').reset_index(drop=True)
new_df['date'] = pd.to_datetime(new_df['date'])

id_cols = ['horse_name_id', 'jockey', 'trainer']
target_cols = ['win', 'top3']
prior_weight = 5 

for col in id_cols:
    # frequency / experience encoding
    freq = new_df.groupby(col)[col].transform('count')
    new_df[f'{col}_freq'] = np.log1p(freq)

    # expanding (leak-free) target encodings
    for target in target_cols:
        global_mean = new_df[target].mean()
        grp = new_df.groupby(col)[target]

        past_sum = grp.cumsum() - new_df[target]     # sum of previous outcomes
        past_cnt = grp.cumcount()                    # number of previous appearances

        new_df[f'{col}_{target}_te'] = (
            past_sum + prior_weight * global_mean
        ) / (past_cnt + prior_weight)

## Mapping location

In [23]:
new_df['location_mapped'] = new_df['location'].map(location_mapping)

## Info Class Mapping

In [24]:
class_mapping = {
    # Gruppe-Rennen (höchste Klasse)
    'Hong Kong Group One': 1.0,
    'Group One': 1.0,
    'Hong Kong Group Two': 2.0,
    'Group Two': 2.0,
    'Hong Kong Group Three': 3.0,
    'Group Three': 3.0,

    # Offene Klassenrennen
    'Class 1': 4.0,
    'Class 2': 5.0,
    'Class 2 (Bonus Prize Money)': 5.1,

    # Alters-/Restriktionsrennen zwischen Class 2 und 3
    '4 Year Olds': 5.3,
    'Restricted Race': 5.4,
    'Griffin Race': 5.5,

    # Class 3 Varianten
    'Class 3': 6.0,
    'Class 3 (Bonus Prize Money)': 6.1,
    'Class 3 (Special Condition)': 6.2,
    'Class 3 (Restricted)': 6.3,

    # Class 4 Varianten
    'Class 4': 7.0,
    'Class 4 (Special Condition)': 7.1,
    'Class 4 (Bonus Prize Money)': 7.2,
    'Class 4 (Restricted)': 7.3,

    # Unterste Klasse
    'Class 5': 8.0,
}
new_df['info_class_mapped'] = new_df['info_class'].map(class_mapping).fillna(8.5)

## Info Rating Mapping

In [25]:
# info_rating sauber in Zahlen aufsplitten
rating_split = (
    new_df['info_rating']
    .str.split('-', expand=True)
    .astype(float)
)

new_df['info_rating_high'] = rating_split[0]        # erstes Zahlensegment
new_df['info_rating_low']  = rating_split[1]        # zweites Zahlensegment
new_df['info_rating_mid']  = rating_split.mean(axis=1)

# fehlende Angaben auffangen
new_df[['info_rating_high', 'info_rating_low', 'info_rating_mid']] = (
    new_df[['info_rating_high', 'info_rating_low', 'info_rating_mid']]
    .fillna(-1)    # oder globalen Mittelwert einsetzen
)

In [26]:
mv_df = new_df.copy()

## Handling Missing Values

In [29]:
# Flaggt alle Spalten, in denen NaNs „keine Historie“ bedeuten
history_cols = [
    'performance_within_conditions_trend', 'performance_within_race_trend',
    'on_date_horse_weight_trend', 'on_date_horse_weight_trend_direction',
    'performance_within_race_rolling_mean_5', 'performance_within_race_rolling_median_5',
    'performance_within_race_ewa_5', 'performance_within_conditions_rolling_mean_5',
    'performance_within_conditions_rolling_median_5', 'performance_within_conditions_ewa_5',
    'place_numeric_rolling_mean_5', 'place_numeric_rolling_median_5', 'place_numeric_ewa_5',
    'weight_trend', 'weight_trend_direction', 'days_since_last_race_any',
    'days_since_last_race_same_season', 'info_rating_high', 'info_rating_low', 'info_rating_mid',
    'on_date_horse_weight', 'draw', 'horse_number'
]
for col in history_cols:
    new_df[f'{col}_missing'] = new_df[col].isna().astype('int8')

In [30]:
trend_cols = [
    'performance_within_conditions_trend', 'performance_within_race_trend',
    'on_date_horse_weight_trend', 'weight_trend'
]
new_df[trend_cols] = new_df[trend_cols].fillna(0.0)

In [31]:
direction_cols = ['on_date_horse_weight_trend_direction', 'weight_trend_direction']
confidence_cols = [
    'on_date_horse_weight_trend_confidence', 'weight_trend_confidence',
    'performance_within_race_trend_confidence', 'performance_within_conditions_trend_confidence'
]

In [32]:
rolling_cols = [
    'performance_within_race_rolling_mean_5', 'performance_within_race_rolling_median_5',
    'performance_within_race_ewa_5', 'performance_within_conditions_rolling_mean_5',
    'performance_within_conditions_rolling_median_5', 'performance_within_conditions_ewa_5',
    'place_numeric_rolling_mean_5', 'place_numeric_rolling_median_5', 'place_numeric_ewa_5'
]
new_df[rolling_cols] = new_df[rolling_cols].fillna(new_df[rolling_cols].median())

In [33]:
new_df['days_since_last_race_any'] = new_df['days_since_last_race_any'].fillna(999)
new_df['days_since_last_race_same_season'] = new_df['days_since_last_race_same_season'].fillna(999)

In [35]:
rating_cols = ['info_rating_high', 'info_rating_low', 'info_rating_mid']
class_medians = new_df.groupby('info_class_mapped')[rating_cols].transform('median')
new_df[rating_cols] = new_df[rating_cols].fillna(class_medians)
new_df[rating_cols] = new_df[rating_cols].fillna(new_df[rating_cols].median())

In [37]:
measure_cols = ['on_date_horse_weight', 'draw', 'horse_number']
new_df[measure_cols] = new_df[measure_cols].fillna(new_df[measure_cols].median())

In [51]:
new_df.isna().sum()

date                            0
location                        0
going                           0
horse_number                    0
horse_name_id                   0
                               ..
info_rating_low_missing         0
info_rating_mid_missing         0
on_date_horse_weight_missing    0
draw_missing                    0
horse_number_missing            0
Length: 82, dtype: int64

In [49]:
direction_cols = ['on_date_horse_weight_trend_direction', 'weight_trend_direction']
new_df[direction_cols] = new_df[direction_cols].fillna(0)

In [50]:
new_df.to_csv('../data/HKHJ_Dataset_After_MV.csv', index=False)